### ISSUE TITLE
question about function  basic_polar_encode

### ISSUE THREAD

**Issue by hahaliu2001** [xiaoshaoning/5g-polar-code#1]
//for below code, why do this index for-loop?
in my understanding we only need do u = mod(u*S,2) once.

for index = 1:n
%   u = multiply_by_S(shuffle(u));    
  v = shuffle(u);
  u = mod(v*S, 2);  
end

**Comment by xiaoshaoning** [comment]
u = mod(u*S, 2) won't give us correct answer.
In the file polar_encoding_implementation.m line 46, we have comment, coded_block = mod(u *G, 2), I think that is what you really mean. The code basic_polar_encode.m uses fast Hadamard transform  which is more efficient than the direct matrix multiplication.
